spring:
  application:
    name: spring-cloud-service-admin

---
spring:
  profiles: peer1
server:
  port: 8762

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: peer2
server:
  port: 8763

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/